### ISSUE TITLE
[Question] Distance from coast in marine API

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#103]
Is there any data in the DWD source you're using (or from another source you've come across) from which you can determine the distance from the requested (or model grid) point to the nearest coastline?  For example, requesting [data for Dublin](https://marine-api.open-meteo.com/v1/marine?latitude=53.3441&longitude=-6.2675&hourly=wave_height) (`latitude: 53.3441, longitude: -6.2675`) returns data for grid point `latitude: 53.25, longitude: -6.25`, which is here:

![image](https://user-images.githubusercontent.com/9009792/184404620-bd1285fc-547f-4c4c-b2bf-b6852c95b56a.png)

It would be useful to know the actual distance from this point to the coastline (and whether it is on a landmass or on water), perhaps as an optional parameter (so that the API endpoint could even be used to return only this information, without any actual wave data).  I suspect that this information is not readily available!

**Comment by Wxglobal** [comment]
Hi think about this request if possibile to add at the api the field thar are in the weather model showing if the lat long requested is on the sea or over the ground or the percent if the request fall.in a grid partilally over the ground and on the sea

**Comment by patrick-zippenfenig** [comment]
@drmrbrewer Currently there is no detailed information about coastlines available.

After gridding data into blocks of 5x5km blocks, each block either has data or it has no data. This only distinguhs between land and sea grid-cell. Even though the coordinate is on land, the model still assumes it is on sea and calculates waves accordingly.

Typically this inaccuracy is not effecting forecast accuracy that much, because waves and weather are not super local.

Something else I want to check is the exact grid coordinates and definition. There could be off-by-one errors and I am also not sure if the coordinate is pointing to the lower-left or center of a grid-cell. 

@Wxglobal for those waves models the landcover percentage is not available. For weather forecast models it is. In this case I split at exactly 50% landcover whether this grid-cell is considered sea or land. For regular forecasts I avoid sea grid-cells, because they tend to have a flat 2 meter temperature forecast as the sea keeps temperatures more stable.

**Comment by drmrbrewer** [comment]
Thanks for the info!

> After gridding data into blocks of 5x5km blocks, each block either has data or it has no data

So I guess this would be a crude (ad spatially coarse) way of determining whether a particular point is over land or over sea.  I'm thinking here of an API that would return this type of information as an option (even without any actual wave or weather data)... could query the marine API and throw away the marine data, just checking if there is data at all (sea) or not (land)... but that seems wasteful of resources.

> for those waves models the landcover percentage is not available. For weather forecast models it is. 

So this would be useful... is this information exposed in the Weather Forecast API?  I can't see that it is... but maybe it could be?

**Comment by Wxglobal** [comment]
Hi Patrick i think adding the percent of soil cover in wx api forecast output i think is a useful info to better trim forecast post processing

**Comment by drmrbrewer** [comment]
@patrick-zippenfenig just wondering if the elevation API could be used for this purpose... particularly if an elevation of `0` can be distinguished between being actual sea (of course at sea level) and land that happens to be exactly at sea level.

e.g.  [this call](https://api.open-meteo.com/v1/elevation?latitude=54.404296875,54.33837890625,54.35211181640625&longitude=18.80859375,18.65478515625,18.6492919921875) can be used to determine which of the three points is over sea (first one) and which are over land (second two).  Of course, we don't know for sure whether `0` really means sea.

**Comment by patrick-zippenfenig** [comment]
@Wxglobal I have created a new issue #108 for landcover fraction in percent. I am not immediately going to add it, because I want to add check if this information is available in other open-data weather-models as-well

@drmrbrewer That looks like an ugly workaround ;-) It also has some edge cases where it does not work reliably because the elevation model does not guarantee to have 0 at the sea and not 0 anywhere else. This would also require a lot of searching to get this information. A better solution would be a polygon coast line dataset.

Still, I doubt that it make a lot of difference for the actual forecast quality.

**Comment by drmrbrewer** [comment]
@patrick-zippenfenig yes it would only work reliably if the elevation model had a special flag for "sea" rather than just assigning it an elevation of `0`... I guess that this is not the case?
