### ISSUE TITLE
Historical weather on specific date

### ISSUE THREAD

**Issue by martijnvanerp** [open-meteo/open-meteo#1057]
For an analysis, I want to know the historical weather on a specific date (for example, August 3) over the past 20 years. Since I can only provide a start_date & end_date, I'm forced to process a massive dataset or make individual calls for each year.

Is there perhaps a more convenient way to solve this?

**Comment by patrick-zippenfenig** [comment]
Hi,
you will have to specify the date for each year. You can do it in one call using coma separated start and end dates: https://archive-api.open-meteo.com/v1/archive?latitude=52.52&longitude=13.41&start_date=2023-09-03,2024-09-03&end_date=2023-09-03,2024-09-03&hourly=temperature_2m

It is not ideal, but the API internally also has to unpack large amounts of data (~2 weeks) just to extract a single day.

In case the API URL becomes too long, you can use POST instead of HTTP GET

**Comment by martijnvanerp** [comment]
Perfect, thanks. 

I use this data to predict the weather on a specific date in te future (>16 days) based on the averages/mean temperature or weather type of the last X years on that date. Wouldn’t this be an idea for an API endpoint as well? Or doesn’t it make any sense meteo-scientific wise?

**Comment by patrick-zippenfenig** [comment]
We might consider adding climate normals (#361) as an additional endpoint. Long-term forecasts using extended range or seasonal models would also be very interesting to predict the range of forecasts for the next weeks/months. The currently available open-data long-term forecasts do not provide good accuracy that I actually would like to use them.
