### ISSUE TITLE
MeteoFrance returns data only for 7 days rather than 10

### ISSUE THREAD

**Issue by MaurizioVacca** [open-meteo/open-meteo#1122]
On the documentation for [MarineAPI](https://open-meteo.com/en/docs/marine-weather-api), when it comes to data availability for MeteoFrance MFWAM, it states

> October 2021 with 10 day forecast

but data stops after 7 days. Infact, running

```
https://marine-api.open-meteo.com/v1/marine?latitude=39.4442&longitude=8.4147&hourly=wave_height&forecast_days=10&models=meteofrance_wave
```

results in `null` being returned for any date past the 7th day from current date.

**Comment by patrick-zippenfenig** [comment]
For unknown reasons the forecasts from MeteoFrance are not updated anymore on Copernicus: https://data.marine.copernicus.eu/product/GLOBAL_ANALYSISFORECAST_WAV_001_027/files?subdataset=cmems_mod_glo_wav_anfc_0.083deg_PT3H-i_202311&path=GLOBAL_ANALYSISFORECAST_WAV_001_027%2Fcmems_mod_glo_wav_anfc_0.083deg_PT3H-i_202311%2F2024%2F11%2F

The last available run is from Thursday 14th last week. I reported the issue to Copernicus and hope it gets fixed soon.

**Comment by patrick-zippenfenig** [comment]
Super quick response from Copernicus Marine Service: The issue is tracked here: https://marine.copernicus.eu/user-corner/user-notification-service?field_category=29&field_product_source=All&field_area=All&field_parameter=All&field_product_type=All&status=All&text=+%5BGLO-781%5D+GLO_ANALYSISFORECAST_%28PHY%7CWAV%29+-+Potential+delays&product_identifier=

**Comment by patrick-zippenfenig** [comment]
The MeteoFrance Wave model has been running smoothly again over the past week

**Comment by patrick-zippenfenig** [comment]
Model updates are listed here: https://open-meteo.com/en/docs/model-updates
