### ISSUE TITLE
Free API Key for Cloudflare

### ISSUE THREAD

**Issue by RedVelocity** [open-meteo/open-meteo#1129]
I've recently moved my hobby weather app from OWM to Open-Meteo, but the deployment has not gone to plan.

It's a remix app hosted on Cloudflare and I seem to run out of daily limit of 10000 easily. 
I'm not exactly sure how free api limits are tracked but they should be less than 1000 for my app usage. 

Is there a way to apply for a free api key? I don't see any option it in my account dashboard or docs.

**Comment by patrick-zippenfenig** [comment]
Hi,  
The API applies limits based on IP addresses. Since services like Cloudflare use shared IPs for multiple users, this can impact your usage as other users also affect the limit. At the moment, there isn’t an automated process to obtain an API key for such scenarios. However, if your application is clearly non-commercial and free of subscriptions or ads, you can email us directly to request a free API key. Thank you!

**Comment by patrick-zippenfenig** [comment]
Update: Cloudflare Workers are no longer rate-limited by IP but by each individual application. This means you should be able to use the weather API on CF workers again and won't be blocked by other users sharing the same IP address on CF. See #1726
