### ISSUE TITLE
[Bug](Weather API) direct_normal_irradiance[0] is always null

### ISSUE THREAD

**Issue by AlienDwarf** [open-meteo/open-meteo#114]
#### Issue Description
The first index of `direct_normal_irradiance` is always null which makes type-safe deserializing pretty rough.
As long as values are `null` you can not deserialize it to a `float[]`.

#### Steps to reproduce the issue
1. Set request hourly to `hourly=direct_normal_irradiance`
2. Check `hourly.direct_normal_irradiance[0]`

#### What's the expected result?
The default value should be 0 to be type-safe _(most languages assert that a number [float,int...] is never "null". Like Java, C, C++, C#)_
The behavior should be like `direct_normal_irradiance_instant`.

#### Additional details / screenshot
Berlin: https://api.open-meteo.com/v1/forecast?latitude=52.5235&longitude=13.4115&hourly=direct_normal_irradiance
London: https://api.open-meteo.com/v1/forecast?latitude=51.5002&longitude=-0.1262&hourly=direct_normal_irradiance
Madrid: https://api.open-meteo.com/v1/forecast?latitude=40.4167&longitude=-3.7033&hourly=direct_normal_irradiance
Tokyo: https://api.open-meteo.com/v1/forecast?latitude=35.6785&longitude=139.6823&hourly=direct_normal_irradiance

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. I applied a fix in https://github.com/open-meteo/open-meteo/commit/42b25d49b31717ee03e14f3762a79a703e0f7c36. It should be deployed to production in the next days

Unfortunately, with `start_data` and `end_date` parameters it is still possible to request data ranges that do not have data and will return `null`. In Swift I can decode to an Optional<Float> to capture nulls. This is quite an annoying limitation of JSON.

An alternative would be to use Protobuf encoding. Would this work well in C# .Net?

**Comment by AlienDwarf** [comment]
I must admit I've stick with JSON until now. I've now read into protobuf and made a few tests with dummy weather data.

So far so good. From what I understand, I need .proto files so I can deserialize? Are these available to download somewhere? 
Because every time I try to deserialize an API request I get null

**Comment by DadiBit** [comment]
> I must admit I've stick with JSON until now. I've now read into protobuf and made a few tests with dummy weather data.
> 
> So far so good. From what I understand, I need .proto files so I can deserialize? Are these available to download somewhere? Because every time I try to deserialize an API request I get null

Yes and no... Because the geocoding api is still a private repo they weren't published. I had a similar issue because some fields were missing (you can check them with tools like [this](https://protobuf-decoder.netlify.app/); on Linux run `base64 some-file.bin` to get the encoded data). You can see a [comment on #76](https://github.com/open-meteo/open-meteo/issues/76#issuecomment-1219883656) where I "explain" (found a "hack" actually) to explain to the library used that there are some fields always missing (you should make them private): please note that in my particular case I didn't need a .proto file, although had to manually craft the class... [Final response type](https://github.com/open-meteo/open-meteo-api-kotlin/blob/903195d5ea0a29bc61d7bcaa3e719c30e8e022c3/lib/src/main/kotlin/com/openmeteo/api/geocoding/response/GeocodingGet.kt)

There is also a strange issue I just found while testing my code refactoring:
![image](https://user-images.githubusercontent.com/38182988/188686638-ff397e0f-00ca-4dfa-87a2-8f268857d23e.png)
Although the postcodes value should be an array of strings, you can see a "new" structure...

In addition to that, there's a bug when downloading protobuf responses: the entry count is always 10.
@patrick-zippenfenig should I open an issue for this bug?
