### ISSUE TITLE
GFS current_weather weathercode is nan

### ISSUE THREAD

**Issue by Ibuprofen** [open-meteo/open-meteo#117]
Hello, thanks for creating the GFS endpoint! I am playing around with that now and noticed that I am seeing a JSON parsing error with the results from the following URL:

https://api.open-meteo.com/v1/gfs?latitude=52.52&longitude=13.41&hourly=temperature_2m&current_weather=true

It looks like the current_weather weathercode is `nan` which is causing the json parser to error.

Thank you!!

**Comment by patrick-zippenfenig** [comment]
Hey @Ibuprofen,

I did not yet implement WMO weather codes for GFS and therefore cannot easily fix it. It is a bit complicated to do properly and correctly estimate thunderstorms. Hopefully I can get a first version done in the next weeks.

Would it help you to remove the JSON attribute for now? Do you have the option to use an `Optional` datatype for now?

**Comment by Ibuprofen** [comment]
All good @patrick-zippenfenig! I was playing around with the endpoint and thought it might be an unknown bug. Thanks!

**Comment by drmrbrewer** [comment]
@patrick-zippenfenig are weather codes provided in the GFS data, or would you have to derive these weather codes based on other available parameters (e.g. if precipitation > 1 then "heavy rain" else if precipitation > 0.5 then "light rain" and so on... obviously also taking account of cloudiness, wind speed, etc)?  I'd thought that it would be a good feature suggestion to add these derived weather codes for any sources that don't provide them in the raw data.  Not sure if there is a known method for this out there.

**Comment by patrick-zippenfenig** [comment]
Implementing weather codes for GFS and other models has been on my list for the last weeks. Now, that more and more models are getting mixed together it is even more important. Otherwise the weather code might be inconsistent with other parameters.

I think it will be mostly a collection of thresholds for various parameters to select different WMO weather codes. Do you already have some resources on that? E.g. cape/lifted index to thunderstorm code

**Comment by drmrbrewer** [comment]
After some brief searching I haven't come across anything definitive.  [This paper](https://rmets.onlinelibrary.wiley.com/doi/pdfdirect/10.1017/S1350482702002049) is interesting, and even if it's overly theoretical and not particularly useful for practical purposes (i.e. coding an algorithm for this), it may have references back to other articles that are of more practical use.  I haven't had time to dig into it but will try to find time later.

**Comment by drmrbrewer** [comment]
@patrick-zippenfenig nice work... I see that these are now appearing in the return data!  It may already be on your to do list, but the weather code table needs to be added to each API that now provides weather codes:

![image](https://user-images.githubusercontent.com/9009792/206739875-231d7104-3530-4861-8d49-fbae6d920f32.png)

**Comment by patrick-zippenfenig** [comment]
Hey, sorry got deeply stuck on working on new datasets ;-)

1. Currently I cannot calculate freezing rain with GFS. I will add `CFRZR` from GFS and test the results with that.
2. Good idea to use `visibility < 1000m`. I have committed a fix. I will deploy it in the next days.
3. I fixed this issue a couple of days ago. The snow classification was wrong. I use the field `CSNOW` directly from GFS. Alternatively wet bulb temperature below 1.2°C is often used to classify snow (although multiple atmospheric levels should be considered)
4. Correct. DWD ICON model calculate weather codes directly. For now, I assume that their calculation is more sophisticated than mine ;-).

Thanks for checking my code and the reminder!

**Comment by patrick-zippenfenig** [comment]
3. Liquid rain at -1°C is plausible. Especially if higher atmospheric levels are slightly warmer. At -2 or -3 is gets more unlikely. On the other hand, it can also snow at +1-2°C ;-). Did you see any liquid rain at <-3°C? Before my bug fix a couple of days ago, there could have been rain at -10°C.
4. Hm, 57% is supposed to be `partly cloudy` according to some older documentation from DWD ICON. Unfortunately, I do not have access to the DWD ICON source code, so it is hard to check, how they actually calculate it. For weather codes like thunderstorms, it would be very interesting to see how they calculate it.

**Comment by patrick-zippenfenig** [comment]
It looks like most of the time it is correct however. For this time-step, GFS `CSNOW` is 0. Technically, I am correctly returning what is forecast in GFS. 

I might add an additional check in the future for temperature. As more and more weather variables are being use to calculate `weahtercode` I probably have to precompute it in order to keep the API fast. This however, is a bit more work...

![Screenshot 2023-01-21 at 16 59 14](https://user-images.githubusercontent.com/11670456/213875409-6df6aa90-602d-4ae3-bfa0-65c1153784b2.png)

**Comment by patrick-zippenfenig** [comment]
I just added `CRAIN` do my download scripts. Maybe it helps to better understand what is happening. Maybe `Categorical Ice Pellets` or `Categorical Freezing Rain` is set. It will take a day, before I have enough data to actually on my servers to actually check it

**Comment by patrick-zippenfenig** [comment]
All available precipitation categories do not indicate any kind of snow, ice pellets or freezing rain for those 0.1mm events. It could be convective snow, but there is no indication for that in GFS either. 

This only effects drizzle at low temperatures, otherwise snow is classified correctly.

So far the only viable solution is to set all precipitation to snow for wet bulb temperatures below 1.3°C. To do this. I would have to build an additional post-processing stage into the GFS downloader to derive weather codes. It will be a couple of hours of work, so I will postpone for now.

![Screenshot 2023-01-26 at 11 48 32](https://user-images.githubusercontent.com/11670456/214817570-f5ec575f-52a1-41da-8e01-11f2c67be4b0.png)

**Comment by patrick-zippenfenig** [comment]
Yes, this would be the desired behaviour.

Additionally there is also the differentiation between large scale and convective precipitation, but the GFS HRRR model is a convection permitting model and does not differentiate anymore.

**Comment by patrick-zippenfenig** [comment]
Good catch! Yes, with GFS013 the weathercode calculation now has to take clouds from GFS013, but visibility from GFS025. I will have a look at it on Thursday
