### ISSUE TITLE
[Suggestion] ACCESS models from Australian Bureau of Meteorology

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#175]
Would be a great addition to open-meteo:

http://www.bom.gov.au/nwp/doc/access/NWPData.shtml

**Comment by patrick-zippenfenig** [comment]
Yes, BOM model would be interesting. Especially since they are based on UKMO which is not open-data. BOM also charges around >$5.000 to get access. I am also unsure about the license. Redistributing under CC-BY might not be possible.

Because of cost and license, I am unsure if and when those models can be added
