### ISSUE TITLE
[Suggestion] make more wind levels available.

### ISSUE THREAD

**Issue by ElSabio97** [open-meteo/open-meteo#208]
Like WindyApp has, many more layers of wind data would be awesome for aviation apps.

**Comment by patrick-zippenfenig** [comment]
Hi, I should have most pressure levels available for various national weather services. The general "Weather Forecast API" does not show all of them, because not all weather providers offer all levels. You would have to specifically select the DWD API, GFS API or MeteoFrance API.

Additionally there are model levels which are defined as meters above ground. Those I did not yet implement, as they are even more inconsistent between weather models.

Ultimately, I might add all model levels and interpolate between multiple levels to make them comparable and present them somehow in an interface. 

The amount of data for pressure and model levels is very high and I would need to upgrade all API nodes to have ~2TB disk space. I am considering to move all upper air variables to a separat API endpoint "upper-level-api.open-meteo.com". This way, I can better scale the regular API onto more servers.

Do you miss any specific levels?

**Comment by ElSabio97** [comment]
I miss nothing. I did not even realize you already have the option `pressure levels` in the URL Generator.

I have this already up and running in my app. Thanks for this amazing API.
