### ISSUE TITLE
get weather data 3 hour period

### ISSUE THREAD

**Issue by jafarpishdadi** [open-meteo/open-meteo#218]
Hi, thanks
How to get the data  api every three hours instead of one hour

**Comment by patrick-zippenfenig** [comment]
Hi, currently 3 hourly data is not offered. One exception is the ECMWF API which offers 3-hourly data https://open-meteo.com/en/docs/ecmwf-api

Otherwise you have to aggregate data yourself. Although 3 hourly data used to be quite common, it can be more confusing for users as it is hard to distinguish at which time it is going to start raining or the daily maximum temperature is not correctly represented as it might be in the middle of 3 hours.
