### ISSUE TITLE
Historical weather API add variable `snow_depth`

### ISSUE THREAD

**Issue by Sarthak-Singh1996** [open-meteo/open-meteo#272]
Hi Thank you for the great work! Is it possible to get the historic data for about 20 years for the parameter snow_depth ?

**Comment by patrick-zippenfenig** [comment]
Hi,

I did not integrate snow cover into the historical weather API mostly mostly due to storage constraints. The original ERA5 reanalysis datasets, that I am using, does offer snow cover. In theory it will be possible to download it, but it will take 1-2 months to download it. Right now, I am not starting a new download, but maybe in a couple of months, I will restart the download to get also some additional weather variables
