### ISSUE TITLE
missing parameters

### ISSUE THREAD

**Issue by m0rp43us** [open-meteo/open-meteo#299]
Hello,

I am currently working on the second updated version of the python SDK and i got into some issues regarding ECMWF,as i was testing the API i discovered that there are some variables that do actually raise errors : 
- divergence_of_wind
- the timezone parameter included in the payload raises an error.

Thanks in advance for the efforts

**Comment by patrick-zippenfenig** [comment]
Hi,
`divergence_of_wind` at different pressure levels seems to work for me. Can you send me the API URL?

Unfortunately, `timezone`  support is not really possible in the ECMWF IFS api, because I used 3-hourly data instead of hourly. All my underlaying code to handle timezones and aggregate to daily values, relies on hourly data. One solution would be to create a `v2` API for ECMWF and switch to hourly values, like all other weather APIs are doing. I wanted to couple this change with the inclusion of more open-data (see #249)

**Comment by m0rp43us** [comment]
Appologies,it is working,i didn't think of it as a pressure level variable.

**Comment by m0rp43us** [comment]
Oh and the second version of the python SDK is out,up to date with the APIs !

**Comment by patrick-zippenfenig** [comment]
Thanks!
