### ISSUE TITLE
Why cannot use commercially?

### ISSUE THREAD

**Issue by qzcool** [open-meteo/open-meteo#30]

**Comment by open-meteo** [comment]
Hi Qiao, thanks for your question. 

I am working on Open-Meteo as a private individual on my spare time. I do not intent to offer commercial offers or generate revenue. Many other companies around open weather data do that already. I am also employed in a similar field and want to be sure not to be in any legal dispute.

Meanwhile open-source developers cannot include weather data because of high fees or their users having to sign-up for API keys. This is the pain-point I am trying to solve. Because I take certain shortcuts to make APIs are fast a possible while still providing good forecasts, I can keep the service running at low operational cost. Weather forecasts for commercial applications in the energy or agronomical sector, profit more from established commercial weather api providers.

Best, Jeff
