### ISSUE TITLE
Direct_normal_irradiance wrong in the morning?

### ISSUE THREAD

**Issue by woheller69** [open-meteo/open-meteo#367]
https://api.open-meteo.com/v1/forecast?latitude=48.17&longitude=11.76&forecast_days=1&hourly=direct_normal_irradiance,diffuse_radiation&timezone=auto

Currently sun rises at 5:10
Why is the value for direct_normal_irradiance still 0.0 at 6:00?
Shouldn't the average of the preceding hour 5:00 to 6:00 be >0 ?

**Comment by patrick-zippenfenig** [comment]
The `direct_radiation` at 6:00 is given as 2 W/m^2 by the weather model. With only 2 watts direct radiation, there are some thresholds that remove radiation in this case. Typically, DNI is not very reliable below 5° solar angle. I am not sure if it is possible to get better DNI results given those circumstances.

https://api.open-meteo.com/v1/forecast?latitude=48.17&longitude=11.76&forecast_days=1&hourly=direct_normal_irradiance,direct_radiation&timezone=auto

**Comment by woheller69** [comment]
are you calculating DNI from direct radiation on the horizontal plane? I thought that works the opposite way...

If direct radiation is 2W/m^2 DNI should be much higher than that but of course it is difficult to calculate.

**Comment by gvzdus** [comment]
I am more unhappy with "direct_normal_irradiance" rather than "direct_radiation". Sample:
https://api.open-meteo.com/v1/forecast?latitude=51.07&longitude=6.59&forecast_days=1&hourly=direct_normal_irradiance,direct_normal_irradiance_instant&timezone=auto
Sample for 06:00 CEST today: 
direct_normal_irradiance = 0 // wrong
direct_normal_irradiance_instant = 31.4 // very reasonable
Reality: Sharp shapes of objects, panels with 30° tilt & 130° azimuth (Southeast) producing 3-4% of kWp.

**Comment by patrick-zippenfenig** [comment]
> are you calculating DNI from direct radiation on the horizontal plane? I thought that works the opposite way...

Yes, DNI is calculated based on `direct_radiation`. Direct radiation is available from most weather models. To calculate DNI, data is super sampled to 1 minute resolution and multiplied by cosine of zenith (see https://github.com/open-meteo/open-meteo/blob/b28f3df63a941687ad9ca05ddb3826fdbb2ab853/Sources/App/Helper/Zensun.swift#L303). I was also working on an analytical solution without super sampling, but have given up after a couple of days. 

All `instant` variables are calculated by the Open-Meteo API as well. Weather models never offer any solar flux variables as instant values.

Reason for 0 watts radiation in the morning could be the limit to 85° zenith angle, but without it, it diverges towards 0 and suddenly you get 500 watts instead of 5. (see https://github.com/open-meteo/open-meteo/blob/b28f3df63a941687ad9ca05ddb3826fdbb2ab853/Sources/App/Helper/Zensun.swift#L439)

> If direct radiation is 2W/m^2 DNI should be much higher than that but of course it is difficult to calculate.

With 2 watts direct radiation averaged over the previous hour, DNI would not be much more than 10 watts. A potential solution could be 15 minutes solar radiation data from the DWD ICON-D2 model (See [DWD API](https://open-meteo.com/en/docs/dwd-api#latitude=52.52&longitude=13.41&minutely_15=direct_radiation,direct_normal_irradiance)). 

![Screenshot 2023-06-16 at 09 27 09](https://github.com/open-meteo/open-meteo/assets/11670456/e4f0aa73-6fa1-4cda-b933-c1e9b01c0656)

**Comment by woheller69** [comment]
"and multiplied by cosine of zenith": isn't it divided by cosine of zenith?

so it can never be lower than direct_radiation

So instead of making it 0.0 it could at least have direct_radiation as min value to reduce the error.

If 15min values are available it would of course be great if it could be calculated from these values in future.

**Comment by woheller69** [comment]
or maybe even

DHI = direct_radiation/cos(85°)  when the zenith angle is > 85°

This is about 11x direct_radiation

**Comment by woheller69** [comment]
let dni = dhi / zzBackwards

would it make sense to also limit zzBackwards to cos(85°) instead of setting dni to 0.0 later on?

**Comment by patrick-zippenfenig** [comment]
Sorry for the confusion. It is using division instead of multiplicand already. Zenith is also limited to 85° beforehand.

> So instead of making it 0.0 it could at least have direct_radiation as min value to reduce the error.

Seems reasonable. This however can mask the underlaying issue. I will implement it for now and check again once I continue working on an analytical solution for DNI with 1 hour backwards averages

**Comment by patrick-zippenfenig** [comment]
With PR #383, the accuracy of DNI has been improved. The discrepancies in previous versions were due to multiple small errors, which resulted in a slight time shift and incorrect modeling of sunrise and sunset times.

The following enhancements have been made:
- The calculation of solar position is now as precise as possible, using the NREL equations with an error margin of only 0.0003° in sun declination. However, to improve runtime performance, coefficients are cached, which reduces accuracy slightly (up to a maximum of 0.02°). Previously, the error could be as high as 1°.
- The solar interpolation routine had a time shift of 30 minutes, which could lead to significant differences in results.
- Thanks to the improved accuracy in solar declination and equation of time, my analytical solution for backward-averaged DNI now works correctly. As the analytical solution does not require super sampling radiation to 1 minute intervals, I can now integrate DNI into the historical weather API.

With the computational improvements, I can now integrate DNI into the historical weather API calculating long time-series of data.

**Comment by patrick-zippenfenig** [comment]
> So instead of making it 0.0 it could at least have direct_radiation as min value to reduce the error.

The artificial limit to greater than `direct_radiation` has also been removed again. I do not like those solutions ;-)

**Comment by woheller69** [comment]
A real fix is of course preferred :-)
