### ISSUE TITLE
DWD API: hourly and minutely_15 precipitation inconsistent

### ISSUE THREAD

**Issue by woheller69** [open-meteo/open-meteo#423]
I would expect that the sum of minutely_15 forecasts equals the hourly value.
But this is not the case.

https://api.open-meteo.com/v1/dwd-icon latitude=48.17&longitude=11.76&hourly=precipitation&minutely_15=precipitation&timezone=auto

![DWD](https://github.com/open-meteo/open-meteo/assets/68678880/ace96bd2-c86f-426f-a490-1b2a627156e3)

e.g. at 12:00 hourly says 0.2mm but sum of quarters gives just 0.1mm
or at 14:00 hourly says 0.1mm and the sum of quarters says 0

I am evaluating minutely_15 forecast to tell when exactly precipitation starts/ends and this inconsistency causes problems.
Is 0.1mm the smallest possible unit? If so, for minutely_15 it would be good to have 0.025 as smallest unit.

**Comment by BlackBird-One** [comment]
Yes, it's a duplicate entry. 
I suspect that because of the units used, we can't expect a solution anytime soon.

**Comment by patrick-zippenfenig** [comment]
Increasing the resolution for rain from 0.1 to 0.025 would improve the situation. However, due to rounding and floating point conversion issues, it would still exist. An option could be to artificially adjust precipitation to "hide" those rounding issues. Needs to be implemented in the de-averaging code: https://github.com/open-meteo/open-meteo/blob/20529cb38c27969dea5b56937eb85ca3e988135f/Sources/App/Helper/Deaveraging.swift#L85 Not quite sure how do to it though...
