### ISSUE TITLE
Error on Ubuntu 22.04: Failed to enable unit: File multi-user.target: Identifier removed

### ISSUE THREAD

**Issue by dzungpv** [open-meteo/open-meteo#426]
I have this error when install on some Ubuntu VPS 22.04:
```
Failed to enable unit: File multi-user.target: Identifier removed
Failed to retrieve unit state: Unit name openmeteo-notify@.service is neither a valid invocation ID nor unit name.
openmeteo-notify@ is a disabled or a static unit, not starting it.
```
It seem occur with some builds like here: https://github.com/containers/podman/issues/12438
Fix available with replace:
```
WantedBy=multi-user.target
```
with 
 ```
WantedBy=default.target
```

**Comment by dzungpv** [comment]
> Thanks! Could you open a PR?

Yes, I open PR https://github.com/open-meteo/open-meteo/pull/427

**Comment by patrick-zippenfenig** [comment]
I checked the new target setting and it does not affect this warning message. I believe it is caused because the APT package tries to `enable` and `start` this systemd service, but it is only a one shot invocation to send emails.

Does this warning prevent running the API in any way?

Note: Please do not mix any other code in the PR like changing the timeout values. Please create separate branch in your repository and a new PR

**Comment by dzungpv** [comment]
Code from here so you can trust it: https://github.com/containers/podman/pull/12449

**Comment by patrick-zippenfenig** [comment]
Thanks for the link! I understood the problem now. PR merged!
