### ISSUE TITLE
FeatureRequest: sunshine duration

### ISSUE THREAD

**Issue by HolgerHees** [open-meteo/open-meteo#467]
Can anybody help me and explain how to calculate the sunshine duration based on provided weather data?

**Comment by patrick-zippenfenig** [comment]
You could take daily `sunrise` and `sunset` times as `unixtimestamps` and subtract them.

There is also an undocumented `daylight_duration` variable which is only available through the climate API. [Example](https://climate-api.open-meteo.com/v1/climate?latitude=52.52&longitude=13.41&start_date=2023-01-01&end_date=2023-12-31&models=CMCC_CM2_VHR4&daily=daylight_duration). I could also enable this feature for the general weather API.

What is your use-case for daylight duration?

**Comment by HolgerHees** [comment]
I mean sunshine. not daylight.

It depends from radiation level . I heared a radiation level above 150W is counted as sunshine.

Currently it is very difficult to calculate. I try to calculate the amount of time where the radiation is above 150W inside a timeslot of 15 minutes.

Means if the previous timeslot has a radiation of 100 and the current timeslot has a radiation of 160, I assume that the sun was shining for 12 minutes.

**Comment by patrick-zippenfenig** [comment]
Yes, there are different definitions for daylight/sunlight. The WMO definition is direct normalised irradiation > 120W/m2. Please note, that numerical weather models typically average solar radiation fluxes over a period of time (15 minutes). Due to non-linear solar zenith angle, it is a pain to calculate it correctly especially during sunrise and sunset.

If you want to calculate it directly, you would have to use a solar position model

**Comment by guidocioni** [comment]
A good approximation of sunshine duration can be based on the value of cloud cover only.
You can multiply the number of minutes of daylight within one hour to the value of fractional cloud cover to get a good approximation of sunshine duration that can be compared at least in the same model. 
Of course you need to consider only hours when there is daylight. 
I've used this in the past and it works pretty well...

**Comment by woheller69** [comment]
I would also like to see "hours of sun" as an additional daily value

**Comment by patrick-zippenfenig** [comment]
`sunshine_duration` for 15-minutely, hourly and daily and `daylight_duration` for daily is now available. Given in seconds.

Daily sunshine duration will always be lower than daylight duration, because the sun will not reach 120 Watts around sunrise/set.

It is based on the WMO definition of `sunlight = DNI > 120 W/m2`. Compared to cloud cover values will be higher, as 120 watts of direct normalised irradiance can be reached at >60% cloud cover.

Implementation can be found here: https://github.com/open-meteo/open-meteo/blob/a914fa7fbe6b83574e35162c3896ab23a7e2c483/Sources/App/Helper/Zensun.swift#L305C3-L305C3. Code duplication is tolerated here, because the solar computations are computationally expensive.

API servers are already updated. API documentation is updated, but it will take a while until the website is deployed.

**Comment by woheller69** [comment]
Thanks. Just trying in my omWeather app. I am a bit surprised, that I am e.g. getting 6h of sunshine_duration on a day with drizzle day symbol (WMO 53) and clouds (WMO 3) in all hourly forecast from sunrise to sunset... Probably it is 121W/m2 all day ?

e.g. day 8:
https://api.open-meteo.com/v1/forecast?latitude=48.18&longitude=11.76&daily=sunshine_duration,weathercode&forecast_days=10&timeformat=unixtime&timezone=auto

**Comment by patrick-zippenfenig** [comment]
On first sight, hourly data looks reasonable. There are some inconsistencies like sunshine at 100% cloud cover at Thursday afternoon, but if drilled down to mid/low/cloud, only high cloud cover is 100%. High clouds typically pass through a lot of light (even 680 W/m2 DNI).

Total cloud cover is directly taken from DWD ICON. For other models I calculate total cloud cover based on mid/low/high and weight high clouds only up to 50%. I am not sure, why DWD ICON sets cloud cover to 100% at 100% high cloud cover.

Given the direct radiation prediction, sunshine calculation is correct. Other days with 100% cloud cover, show clearly no sunshine duration. However, it is questionable if the direct radiation forecast is correct and whether the 120 watts limit might be too low.

As the daily weather code is only taking the worst condition within 24 hours, this might not represent the weather condition throughout the daylight time correctly. For usability, it might be worth to calculate the cloudiness time based `sunshine_duration / daylight_duration` and pick a weather icon accordingly.

DWD ICON model:

![Screenshot 2023-11-15 at 09 43 38](https://github.com/open-meteo/open-meteo/assets/11670456/964a5478-d3fc-42f7-b44a-0edc498a231f)

GFS model show similar results

![Screenshot 2023-11-15 at 09 56 23](https://github.com/open-meteo/open-meteo/assets/11670456/76dcb334-c00b-4dee-8030-7037c7d36e1d)
