### ISSUE TITLE
No snow depth data for ICON-D2-EPS

### ISSUE THREAD

**Issue by guidocioni** [open-meteo/open-meteo#483]
Among the ICON ensembles, snow depth is only available on the German domain, i.e. ICON-D2-EPS, in the open data server (https://opendata.dwd.de/weather/nwp/icon-d2-eps/grib/00/h_snow/). However there seems to be no snow depth ingested in open-meteo for ICON-D2-EPS.
Was this a specific choice?

**Comment by patrick-zippenfenig** [comment]
Thanks for reporting! I probably did not enable snow depth for ICON-D2-EPS, because it is not available for other ICON EPS domains. This commit enables it: https://github.com/open-meteo/open-meteo/commit/be8378842071cb62697ba0bef4b99bb519a116e7

It will take a couple of days until it is available on the public API servers.

**Comment by guidocioni** [comment]
thank you @patrick-zippenfenig for the quick feedback! as snow depth is missing for most ensemble models at high resolutions it is really important to get it from ICON-D2-EPS. keep up the good work
