### ISSUE TITLE
cloudcover always the same as cloudcover_low and cloudcover_mid always the same as cloudcover_high

### ISSUE THREAD

**Issue by EnderPicture** [open-meteo/open-meteo#50]
Hi, 

I have noticed that `cloudcover` == `cloudcover_low` and `cloudcover_mid` == `cloudcover_high` is this the intended output? I've tried many city presets in the [doc](https://open-meteo.com/en/docs) and the output graph always only has 2 lines where each of the two pairs stack and don't deviate.

[demo api call](https://api.open-meteo.com/v1/forecast?latitude=52.5235&longitude=13.4115&hourly=cloudcover,cloudcover_low,cloudcover_mid,cloudcover_high)

output graph
![image](https://user-images.githubusercontent.com/16552062/140868537-17e5a799-6c11-443b-8b7e-83079b55b22c.png)

**Comment by open-meteo** [comment]
Thanks for reporting! It took a while to correct this issue, but it is now corrected!

**Comment by drmrbrewer** [comment]
Will this fix take a little while to feed through to the live data?

**Comment by open-meteo** [comment]
It is already live

**Comment by drmrbrewer** [comment]
At least high and mid are still always the same?

![image](https://user-images.githubusercontent.com/9009792/142046345-9a2557f3-53f2-4505-b2de-0b6555887de2.png)

https://api.open-meteo.com/v1/forecast?latitude=40.438&longitude=-3.8196&hourly=cloudcover,cloudcover_low,cloudcover_mid,cloudcover_high

**Comment by open-meteo** [comment]
You are right! Thanks!

It is now corrected and showing the right values

![Screenshot 2021-11-16 at 20 16 38](https://user-images.githubusercontent.com/86407831/142050797-9aa8dc1e-65dd-4462-bdb4-8582598cc8de.png)

**Comment by drmrbrewer** [comment]
Thanks!  Any idea why the cloud cover data seems to be more "linear" than e.g. temperature?  The plot is often made up of straight-line segments, with several points along the straight line, almost as if the true time resolution is lower than 1 hour... looks like the actual turning points are at 3-hourly intervals.

![image](https://user-images.githubusercontent.com/9009792/142051713-c7b964a4-cc2e-4423-9f74-c6448c3ebb23.png)

**Comment by open-meteo** [comment]
The forecast is "stitched together" from local and global forecasts. Local models only have forecasts until 3-5 days. Global forecasts do not offer proper 1-hourly data after 5 or 6 days. Hourly data afterwards is then interpolated.

For temperature I use some "smart" interpolation routines that take the typical temperature curvature into account. For Cloudcover, I resort to linear interpolation. So far I did not find a better approach. For other parameters like solar radiation also sun inclination is used.

This complexity is nicely abstracted in the APIs, because they work globally and just use the best available weather models
