### ISSUE TITLE
No precipitation data at all

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [open-meteo/open-meteo#554]
There is no precipitation data for any location:

![image](https://github.com/open-meteo/open-meteo/assets/77451351/364cdea9-ed2a-4441-9033-007fa49c81e3)
![image](https://github.com/open-meteo/open-meteo/assets/77451351/66e0b87b-8330-4c25-8ebf-6e0ea81b67ba)
https://open-meteo.com/en/docs#hourly=precipitation_probability

**Comment by patrick-zippenfenig** [comment]
Thanks for the report! I fixed the issue already. A new server did not yet download precipitation probability

**Comment by FleetAdmiralJakob** [comment]
Ok, thank you! What was excactly going wrong? I'm just curious.

**Comment by patrick-zippenfenig** [comment]
I am currently [restructuring](https://github.com/open-meteo/open-meteo/pull/543) the underlaying database files and how data is synchronised. In this case, one model used the wrong name which then was not picked up by the synchronisation process. This only effected precipitation probability because it is generated from the GFS ensemble model in a dedicated step.

The new database structure and synchronisation process should avoid issues like this in the future. The old layout was quite a mess, but at that time, I did not anticipate that many weather models
