### ISSUE TITLE
Sunrise and sunset times half hour off

### ISSUE THREAD

**Issue by cyberorg** [open-meteo/open-meteo#655]
Hi, thanks for the great service you are providing.

Here is the earlier mention of the issue: #246 

Here is the problem:
I am using : https://api.open-meteo.com/v1/forecast?latitude=32.036973&longitude=76.708624&hourly=cloud_cover,visibility,direct_radiation,uv_index,uv_index_clear_sky&daily=sunrise,sunset,sunshine_duration,precipitation_hours,precipitation_probability_max&timezone=auto&forecast_days=1&models=gfs_seamless

Or with timezone specified:
https://api.open-meteo.com/v1/forecast?latitude=32.036973&longitude=76.708624&hourly=cloud_cover,visibility,direct_radiation,uv_index,uv_index_clear_sky&daily=sunrise,sunset,sunshine_duration,precipitation_hours,precipitation_probability_max&timezone=Asia/Kolkata&forecast_days=1&models=gfs_seamless

BTW, Asia/Kolkata timezone is +5:30

Which shows Sunrise/Sunset 7:36/18:37 while the actual times are 7:06 and 18:07 

The closest location is: https://www.timeanddate.com/sun/india/dharamshala where correct times are shown.

So the times needs to be corrected.

**Comment by patrick-zippenfenig** [comment]
Thanks for the report. Looks like a `just` timezone offset calculation issue. #246 had solar position imprecisions. I will try to fix it in the next days.

**Comment by guidocioni** [comment]
Also @cyberorg note that you could compute on your own the sunrise/sunset times. There are many approximated formulations that work pretty well in Python, for example this is the one I implemented in my app https://github.com/guidocioni/point_wx/blob/main/src/utils/suntimes.py.

Why implement a local calculation when you can use the API you say? 
Well, on top of reducing the data transmitted (which has to be redundant for sunrise/sunset times if you request data with granularity finer than daily) the time spent computing sunrise/sunset times is less than the one spent requesting and downloading the data from the API :)

**Comment by patrick-zippenfenig** [comment]
Fix is now committed and will be deployed in the next hours.

Note: Open-Meteo is using solar position algorithms (SPA) from NREL ([src](https://github.com/open-meteo/open-meteo/blob/main/Sources/CHelper/src/spa.c) and [swift wrapper](https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Helper/Solar/SolarPositionAlgorithm.swift)). IIRC they provide the best accuracy. There are many simplified SPA routines based in harmonics. Many of those only have a limited valid time of 50 years. Afterwards they do not provide accurate position calculations anymore. Those bugs are hard to catch, because the solar position error varies from month to month. Correct SPA are important for many solar radiation calculations like tilted radiation.

**Comment by jose-nullstudio** [comment]
Just wanted to mention that I am now seeing this same issue again with every city that I've queried for. Sunrise/sunset appear to be around a half hour off.
