### ISSUE TITLE
ECMWF: is it possible to add more soil variables?

### ISSUE THREAD

**Issue by PavelSyomin** [open-meteo/open-meteo#658]
Hi, I have two questions regarding ECMWF models in Weather and History API.

[ECMWF API](https://open-meteo.com/en/docs/ecmwf-api/), according to the docs, provides access to only one soil variable, that is, Soil Temperature (0-7 cm). [History API](https://open-meteo.com/en/docs/historical-weather-api/) that uses almost the same base model (as far as I understand — maybe I'm wrong) allows to access 8 weather variables: 4 for soil temperature (including temperature at 0–7 cm) and 4 for soil moisture.

The questions are:
- what is the reason for this difference in the number of weather variables in ECMWF Weather API and History API?
- is it possible to include weather variables from History API to ECMWF Weather API?

Thanks in advance!

**Comment by patrick-zippenfenig** [comment]
Hi,

The `ECMWF API` is using open-data ECMWF IFS forecasts. It recently got [updated to 0.25°](https://openmeteo.substack.com/p/ecmwf-ifs-upgraded-to-025-resolution). However, only a limited number of weather variables can be accessed as open-data.

The `Historical Weather API` uses ECMWF IFS at full 9-km resolution with access to more weather variables (theoretically all, but I only process dubstep due to storage constraints). However, this data can only be offered for the past. I am not allowed to redistribute any forecast data. This is mainly due to licensing constraints from ECMWF, therefore it is also not possible to include more forecast data into the `ECMWF API`.

This will improve in the future if ECMWF makes more and more data available as open-data.
