### ISSUE TITLE
negative radiation values

### ISSUE THREAD

**Issue by christiancons** [open-meteo/open-meteo#663]
Hallo together,

Since today around noon, I receive negative values `radiation_diffuse`, `radiation_direct`, and `radiation_shortwave` when requesting the hourly forecast using the API. The unit of the radiation values is "W/m^2" and, therefore, should only be positive or zero.

In the case, the negative radiation values are on purpose, how can I interpret them?

The unexpected behaviour can be reproduced when requesting the data using
**https://api.open-meteo.com/v1/forecast?latitude=49.51&longitude=12.54&hourly=temperature_2m,shortwave_radiation,direct_radiation,diffuse_radiation**

We use the **https://customer-api.open-meteo.com/v1/forecast** with our api-key

I also made a screenshot:
![image](https://github.com/open-meteo/open-meteo/assets/160154186/840f327e-88e8-4d5c-94ec-de388dae62d3)

Can someone tell me how this is possible or what it means?
Thank you!

Regards
Christian

**Comment by patrick-zippenfenig** [comment]
Hi, thanks for the report. That is indeed quite surprising. There are only negative values this evening, but past and forecast days are fine... I am investigating...

**Comment by woheller69** [comment]
https://github.com/woheller69/solxpect/issues/16

same here

**Comment by patrick-zippenfenig** [comment]
Issue has been fixed. I was updating servers earlier today and I assume a [change in the eccodes library](https://confluence.ecmwf.int/display/ECC/History+of+Changes) changed the behaviour with sub hourly GRIB files. Only ICON-D2 was affected. The new code should be more reliable in general as it is using a dedicated GRIB reader that has been in use for all other GRIB files. I initially did not upgrade ICON GRIB files due to non standard decoding of sub hourly files

**Comment by christiancons** [comment]
Thank you for the super fast reaction, Patrick!
Seems to work properly again :)
