### ISSUE TITLE
hourly precipitation != rain+showers+snowfall

### ISSUE THREAD

**Issue by farfromrefug** [open-meteo/open-meteo#687]
I am seeing some weird data with this:
https://api.open-meteo.com/v1/forecast?forecast_days=8&forecast_hours=74&forecast_minutely_15=4&hourly=precipitation_probability%2Cprecipitation%2Crain%2Cshowers%2Csnow_depth%2Csnowfall%2Cweathercode%2Ccloudcover%2Cwindspeed_10m%2Cwinddirection_10m%2Cwindgusts_10m%2Cis_day%2Cfreezinglevel_height%2Csnow_depth%2Ctemperature_2m&current=weathercode%2Cis_day%2Ccloudcover%2Cwindspeed_10m%2Cwinddirection_10m%2Cwindgusts_10m%2Ctemperature_2m&minutely_15=precipitation&daily=weathercode%2Cuv_index_max%2Cprecipitation_sum%2Cprecipitation_probability_max%2Cwindspeed_10m_max%2Cwindgusts_10m_max%2Cwinddirection_10m_dominant%2Crain_sum%2Csnowfall_sum%2Cshowers_sum%2Ctemperature_2m_max%2Ctemperature_2m_min&models=best_match&timeformat=unixtime&timezone=Africa%2FAccra&latitude=45.7573298&longitude=6.5394475

If you look at hourly data. like for Mon, 11 Mar 2024 16:00:00 GMT i get `precipitation=0.9` but `snowfall,rain,showers` are all 0.
Is that a bug or am i missing something?

BTW how is precipitation computed? is it rain+snowfall/7+showers?

EDIT: i see more inconsistencies with that same data which i attach in case you cant call it directly.
[forecast.json](https://github.com/open-meteo/open-meteo/files/14555473/forecast.json)
* for Mon, 11 Mar 2024 19:00:00 GMT(index 12) i get an `weather_code` of 85 (Snow shower(s), slight) with snowfall of 1.54 cm (which seems ok) 
* for the next hour Mon, 11 Mar 2024 20:00:00 GMT(index 13) i get an `weather_code` of 86 (Snow shower(s), moderate or heavy) with snowfall of only 0.07 cm ! That does not seem right
* the current weather weather_code/cloudCover does not seem correct. I get 56% cloud cover with clear sky(weather_code 1). Looking at the weather code i dont think we should get 1 with 56% cloudCover

**Comment by 0-5-0** [comment]
Has anyone else been able to reproduce this from open-meteo?

**Comment by patrick-zippenfenig** [comment]
Hi,
sorry for the late reply. I started fixing the issue right away but observed the situation for a while. The main issue was caused by ICON models which for some reason forecast snowfall at ground temperatures of 5-10°C. I added a post-processing step  to convert snow to rain for high ground temperatures https://github.com/open-meteo/open-meteo/pull/714. I used the[ same thresholds](https://gitlab.dkrz.de/icon/icon-model/-/blob/release-2024.01-public/src/atm_phy_nwp/mo_nh_interface_nwp.f90?ref_type=heads#L2232) as ICON models use internally to convert snow to rain in case of higher temperatures.

> BTW how is precipitation computed? is it rain+snowfall/7+showers?

This is correct for most weather models. Snowfall water equivalent is converted with a factor of 1 mm liquid water = 7 mm snowfall.

**Comment by farfromrefug** [comment]
@patrick-zippenfenig thanks for the answer. Saw your commits and thought it could be related to this.
So is that already in prod? Do you want me to start and look at if it is correct now ? (season is changing now, so less snow :))

**Comment by patrick-zippenfenig** [comment]
Yes, it is already live. I am certain there will be more issues :D

**Comment by patrick-zippenfenig** [comment]
After an additional round of checking, data seems to be ok for now. Please comment and reopen if you notice any more issues.
