### ISSUE TITLE
precipitation_probability > 0 but precipitation = 0

### ISSUE THREAD

**Issue by lollita** [open-meteo/open-meteo#783]
I often get:
precipitation_probability>0 and (precipitation = 0 and rain=0)
How it is possible?

**Comment by patrick-zippenfenig** [comment]
Precipitation amount is based on deterministic weather models. There is only "one" weather simulation with either rain yes/no and the amount.

Precipitation probabilities use many (50+) weather simulations with perturbed initial conditions to account for a wide range of uncertainties. The probability is then computed by analysing all runs and check if they predict rain.

Precipitation amount is thus the rain forecast of the most likely outcome, while precipitation probability tells you how many other weather simulations show rain.

**Comment by Leftium** [comment]
Here is the opposite case: precipitation probability = 0 but amount > 0.

I think I understand how this can happen, but it can be confusing/counter-intuitive:

> Precipitation amount is thus the rain forecast of the most likely outcome, while precipitation probability tells you how many other weather simulations show rain.

My question: is precipitation probability or amount more significant when rendering/reading the weather forecast?

In the image below, Wed has 81% probability, but only .04in. Contrast with Fri which has only 0% probability but over 4X the amount (0.18in).

When using other API's that provide both precipitation probability and amount (DarkSky, OpenWeather), I thought the probability was fairly correlated to the amount. And the amount was more useful information than probability in the forecast (in terms of deciding if an umbrella was needed or not).

On the other hand, many other forecasts don't even show Fri's weather condition as rainy. (This may be because other forecast models do not predict any amount of precipitation.)

(This is probably not a bug in Open-Meteo, but it's an interesting point for discussion.)

![image](https://github.com/open-meteo/open-meteo/assets/381217/12320741-5f0a-46e9-823a-f8bada9a4298)

**Comment by lollita** [comment]
Also wmo=51 not have precipitation probability and precipitation .

**Comment by patrick-zippenfenig** [comment]
For which regions did you observe `precipitation probability = 0 but amount > 0`? Currently this can only happen in North America with the HRRR domain. The reason is that the high resolution HRRR model may forecast convective rain that is not present in the GFS model.

In the future this will improve, because the successor of HRRR will also offer ensemble models like European Models do. It might be available end of this year.

**Comment by Leftium** [comment]
> For which regions did you observe `precipitation probability = 0 but amount > 0`?

This was in Korea. BriefSky doesn't display the location info, so I'm not sure how accurate this info is:
- 37.647,126.661
- Bupyeong-gu
