### ISSUE TITLE
DMI seamless only seems to return DMI without ECMWF (self hosted)

### ISSUE THREAD

**Issue by drmrbrewer** [open-meteo/open-meteo#907]
My understanding is that the "seamless" dmi model uses DMI primarily and fills in any gaps with ECMWF (particularly after 2.5 days):

https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m&models=dmi_seamless

I'm playing with the self-hosted api, and am downloading both datasets:

`/etc/cron.d/params.sh; /usr/local/bin/openmeteo-api sync dmi_harmonie_arome_europe "$PARAMS"`

where `PARAMS` is defined in `/etc/cron.d/params.sh` (to declutter and for re-use with other models).

Rather than fetching from AWS I'm downloading the ICMWF with the following...

`/usr/local/bin/openmeteo-api download-ecmwf`

... yes I could fetch `ecmwf` from AWS and maybe I will in future, but that's the way it is now.  Both sets of data end up in the same `data` folder and in the same format, so it shouldn't matter?

Anyway, I'm finding that the equivalent API call to the above (passing `models=dmi_seamless`) is only returning 2.5 days of data... i.e. apparently only the DMI data, and not filling in with ECMWF data.  All the data seems to be there, and indeed passing `models=ecmwf_ifs04` instead does show the ECMWF data.

Do I need to do anything special to get `seamless` to work?

**Comment by drmrbrewer** [comment]
@phillipseamore I have whatever `openmeteo-api download-ecmwf` is giving me... and from the `data` folder it seems that this is only `ecmwf_ifs04`.  How can we get a list of available sub-models?  The [docs states](https://github.com/open-meteo/open-meteo/blob/main/docs/downloading-datasets.md#ecmwf-ifs) that there is only one domain available for ecmwf ifs but I suppose that is not up to date.  From [here](https://github.com/open-meteo/open-meteo/blob/main/docs/cronjobs.md) I can see there is a choice of `domain` (`ifs025` or `aifs025`) but I don't know what those correspond to how to find out (for sure) if these are the only options.  I guess I need to state `--domain ifs025` to get the fill-in data?  But what is `aifs025`?

**Comment by drmrbrewer** [comment]
I'll try that, but is there any way to get `openmeteo-api` to output a list of available domains for a particular model command e.g. `download-ecmwf`?

**Comment by patrick-zippenfenig** [comment]
`download-ecmwf` is the only download command that accepts a `--domain` parameter. I was added later. Typically if you misspell a model name, you will receive a list of accepted models. Otherwise a list of ECMWF models is available in the source code: https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Ecmwf/EcmwfDomain.swift

Please note: I noticed some download issues with KNMI and DMI harmonie models. They still require some attention to ensure data is always up to date. Download speed / bandwidth is a limiting factor. The more users download models from national weather services, the worse it gets. In case of DMI and KNMI you have to download the entire model-output with "all" weather variables even if you only use a small subset of 5 or 6 variables. Please consider using the AWS distribution and only get the required weather variables.

This used to be a huge issue with NCEP GFS after they upgraded from 0.5° to 0.25°. For the first couple of months it was almost impossible to download model data and required workarounds like proxying through [Internet2](https://en.wikipedia.org/wiki/Internet2) to circumvent bandwidth issues.

**Comment by drmrbrewer** [comment]
Thanks, @patrick-zippenfenig, and I agree that fetching from AWS makes more sense, not only to relieve pressure on the original source but also to avoid pointless duplication of file processing, which only serves to use more power and pump more heat into the atmosphere!  Will definitely start using `sync` rather than `download`, especially now that I see how easy it is... it's a direct drop-in replacement without any other changes required.  

And it seems to me that `sync` for a particular model can be repeated on a relatively short (and arbitrary) interval, regardless of which model it is and when the remote files actually change, e.g. every 10 mins, because it doesn't re-fetch what it already has... indeed as the name `sync` implies?  The only additional overhead is to fetch and check a small file/date/time listing?

**Comment by patrick-zippenfenig** [comment]
Correct. It checks for modification dates and only transfers modified files. In later versions I would also like to use web sockets to listen to changes to the S3 repository and copy files immediately. Unfortunately, I haven't figured out how SNS can be used outside of AWS.
