### ISSUE TITLE
UV index history

### ISSUE THREAD

**Issue by mforets** [open-meteo/open-meteo#913]
Hello, 
I've seen that `UV Index` is a daily weather variable in the forecast endpoint, but it is not listed as a weather variable in the historical endpoint (https://open-meteo.com/en/docs/historical-weather-api).

Is this intentional? Can we add it?

**Comment by patrick-zippenfenig** [comment]
Hi,
UV radiation has not been downloaded from the reanalysis weather models. It can be added, but it may take multiple months to download the required data. There are also additional variables I would like to download, so I may start another download session in a couple of weeks

**Comment by mforets** [comment]
Ok gotcha, thanks for your prompt reply!

Should I close this issue or you'd rather keep it around?

**Comment by patrick-zippenfenig** [comment]
Lets keep it open for now. I will create an aggregator ticket with a list of additional variables to add to the reanalysis models.

**Comment by patrick-zippenfenig** [comment]
I checked the reanalysis models again and it turns out they use a different spectrum of UV radiation. It is therefore not possible to derive UV index from them.

There are some paper discussion options to use uv, ozone and cloud cover with neural networks, but its way too complicated https://www.nature.com/articles/s41598-021-84396-2

Historical UV index remains therefore limited to weather models: https://open-meteo.com/en/docs/historical-forecast-api#start_date=2024-01-01&end_date=2024-09-01&hourly=uv_index
