### ISSUE TITLE
Suggestion : Add an autocomplete api for the geocoding Api

### ISSUE THREAD

**Issue by Reyshyram** [open-meteo/open-meteo#93]
Hello, first of all I would like to thank you for your work which allows me to have a free weather api. 

I have a suggestion, why not add an auto-completion api for the geocoding api? Indeed, if the spelling of the name of the city is not exact, the api finds nothing. For example, if I write Val d'Isère, the api doesn't find anything, it only finds the city when I write Val-D'Isère, which can be annoying for the user.

If it’s not possible, do you know a free autocomplete api for city’s names ?

Thanks again for your excellent work.

**Comment by patrick-zippenfenig** [comment]
Hi @Reyshyram,

that would be indeed a good improvement. I will add some test cases and try to fix search results for `Val d'Isère`.

For autocomplete you can also call the Geocoding API for every keystroke (maybe add a 200ms delay) and show results. This mimics the behaviour of a autocomplete API.

There do you plan to use the Geocoding API?

I want to improve the API documentation page soon with a integrated location name search instead of a large drop-down. Most likely [select2](https://select2.org) could be a good library for that.

**Comment by Reyshyram** [comment]
Ok, thanks for your answer, I will check the geocoding api.

**Comment by patrick-zippenfenig** [comment]
Closing for cleanup. Feel free to reopen if you have more questions
