### ISSUE TITLE
Too slow to build OM files ?

### ISSUE THREAD

**Issue by leneon314** [open-meteo/open-meteo#94]
Hey, first thank you very much for the great work !
I noticed that building the OM files in the DonwloadCommands takes too long ( for the icon global domain for example it takes 30/40 min) for each variable ? Is that a correct behaviour ? is there a way to speed up the process? 
I see that your cronjobs are scheduled close to each other, with the number of variables i beleive that commands are lanuched before the previous ones are finished, how do you manage to make this work without issues ?

Thanks again for you fantastic work.

**Comment by patrick-zippenfenig** [comment]
Are you using a `debug` or `release` build? `debug` build are significantly slower in converting files

All weather variables for ICON global should take less than 1 hour. Most of the time is spend downloading.

**Comment by patrick-zippenfenig** [comment]
@leneon314 did you successfully setup the API? What pain-points did you encounter? The project is very new and the documentation definitely need improvements. Any suggestions?

**Comment by leneon314** [comment]
> @leneon314 did you successfully setup the API? What pain-points did you encounter? The project is very new and the documentation definitely need improvements. Any suggestions?

Yes i ,it is straight forward (i used the native setup and the prebuild for linux as well), the setup is easy with your documentation (at least for me). For the installation i don't think there is a need for more, for the API itself the list of pending enahcements you have seems to be very good. May be having a schedule of the upcoming functionalities would be great. Are you alone contributing to this  ? Do you need some help ?
Thank you very much for your work.

**Comment by patrick-zippenfenig** [comment]
@leneon314, glad you made it work!

Yes, so far I am the only main contributor. @kikocorreoso is also helping out! The project went open source just a week ago ;-)

A rough schedule looks like:
- Marine forecast for waves. The [first version](https://open-meteo.com/en/docs/marine-weather-api) is just to be released.
- Air quality forecast is currently in [testing](https://open-meteo.com/en/docs/air-quality-api) and could be ready next week
- Automatic timezone detection (#91)
- DWD MOSMIX integration for nowcasting in populated areas
- High resolution North America forecasts (#83)
- Integrate seasonal weather forecasts for up to 6 months
- Integrate ensemble models for 14 days forecast with uncertainties

In the longer term:
- Improve webdesign
- Use the Geolocation API in the API documentation to select locations (instead of fixed drop down)
- Build a simple "location weather forecast" to make forecasts easily available
- Integrate open-data weather models from: FNMI, MeteoFrance, GEM, KNMI
- Contact MeteoSwiss, UK MetOffice of their models could be used as well
- Integrate radar and satellite observations for nowcast corrections
- Build maps API to generate OSM compatible raster/vector tiles (weather data storage needs to be optimised for this use-case)

In general:
- SDKs for various programming languages
- Tutorials and instructions how to use Weather APIs (e.g. demo apps like in #76 )

Help is absolutely appreciated! 

The code of Open-Meteo is probably not an easy way to start. So you have some experience in API development, SDKs, web-development, web-design or technical writing?

**Comment by leneon314** [comment]
@patrick-zippenfenig 
The rough schedule looks good.  May be you could add GFS model asap, it got some weather varibales that are not offered by ICON (to predict thundertorms for example)

I have a ready to use api (based on nodejs) to determine timezone from lat/lon that i could provide,  but I would beleive that you expect something in swift to keep API performance high.


 i'am passionate about weather ,  I have experience in API , android app , linux scripting dev...

**Comment by patrick-zippenfenig** [comment]
Are you referring to CAPE and lifted index for thunderstorms? ICON is forecasting thunderstorms as indicated by weather codes. Only hail forecasts are limited to Central Europe, because they require high model resolution and even then, they are not very reliable.

GFS is definitely on the high priority list, but will also require a lot of storage and I might hit more issues than expected. I wanted to start with seasonal forecast as a quick win ;-)

For the timeline API I wanted to use the C library from [timezone boundary builder](https://github.com/evansiroky/timezone-boundary-builder). Should be less than 50 loc ;-). Yes, I want to keep it in swift, because I do not want to do an API roundtrip to resolve timezones.

I will write some "good first issue" tickets, maybe you could help out with some tasks  👍

**Comment by decarbonise** [comment]
>     * Integrate open-data weather models from: FNMI, MeteoFrance, GEM, KNMI

KNMI and FMI would be great whenever anyone gets a chance!
