### ISSUE TITLE
Source of Recent Historical Weather Data 

### ISSUE THREAD

**Issue by david5010** [open-meteo/open-meteo#960]
Hi,

I wanted to ask for clarification. It seems that the historical data is usually ERA5. However, ERA5 usually has a 5 day lag on Copernicus. I tried getting the recent historical data (of today, yesterday...etc.) and I did get some results. Are those values from ERA5 as well or a different source?

**Comment by patrick-zippenfenig** [comment]
Hi,
if you select the model "ERA5-Seamless" you will only receive ERA5 and ERA5-Land data: https://open-meteo.com/en/docs/historical-weather-api#models=era5_seamless

Per default the historical weather API will also use ECMWF IFS (HRES 9km) data.

The historical forecast API will return past data from high resolution weather models. In this case there is no delay, because this time-series is assembled by combining all available weather model runs.

**Comment by hcweigand10** [comment]
Maybe I'm missing something, but I still have a similar question to the original. If I query the historical weather API for data from today, I get results. What is the source of this data? The IFS model has a delay of 2 days, so it can't be that or ERA5, right?

**Comment by patrick-zippenfenig** [comment]
It's IFS HRES. Since October 1st 2025 the ECMWF policy changed and we are allowed to redistribute IFS HRES data without 2-day delay. The docs still need to be updated
